### ISSUE TITLE
第１１章　11.4 本番環境でのメール送信

### ISSUE THREAD

**Issue by YukiT1990** [YukiT1990/sample_app-RoRT#10]
本番環境からユーザーの新規登録を行おうとする（情報を入力してcreate my accountボタンを押す）と

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

というエラーになった。ボタンを押すと認証されていないユーザーが作成された状態になっている。

（画像）
https://gyazo.com/216a1adf0eb488a13ac218db0226d22b

heroku logs

~~~
ec2-user:~/environment/sample_app (master) $ heroku logs
2019-08-15T16:15:13.595472+00:00 app[web.1]: I, [2019-08-15T16:15:13.595345 #12]  INFO -- : [3c1c050f-5634-4c76-b1ea-706747d57721]   Rendered layouts/_rails_default.html.erb (1.9ms)
2019-08-15T16:15:13.596607+00:00 app[web.1]: I, [2019-08-15T16:15:13.596528 #12]  INFO -- : [3c1c050f-5634-4c76-b1ea-706747d57721]   Rendered layouts/_shim.html.erb (0.3ms)
2019-08-15T16:15:13.602883+00:00 app[web.1]: I, [2019-08-15T16:15:13.602804 #12]  INFO -- : [3c1c050f-5634-4c76-b1ea-706747d57721]   Rendered layouts/_header.html.erb (5.5ms)
2019-08-15T16:15:13.604416+00:00 app[web.1]: I, [2019-08-15T16:15:13.604335 #12]  INFO -- : [3c1c050f-5634-4c76-b1ea-706747d57721]   Rendered layouts/_footer.html.erb (0.5ms)
2019-08-15T16:15:13.605035+00:00 app[web.1]: I, [2019-08-15T16:15:13.604956 #12]  INFO -- : [3c1c050f-5634-4c76-b1ea-706747d57721] Completed 200 OK in 1200ms (Views: 1060.6ms | ActiveRecord: 27.1ms)
2019-08-15T16:15:13.818183+00:00 heroku[router]: at=info method=GET path="/assets/application-7fb8fba2ed437fb9bade6f34a7b3d5872286cc44540e6bc3e649d8982b7669ac.js" host=vast-brushlands-26233.herokuapp.com request_id=246bf575-c977-42ca-9145-cc7838d98ce6 fwd="46.193.65.129" dyno=web.1 connect=0ms service=4ms status=304 bytes=112 protocol=https
2019-08-15T16:15:13.934138+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=vast-brushlands-26233.herokuapp.com request_id=173e17de-6fa5-4e56-9a16-172df6c3b1f4 fwd="46.193.65.129" dyno=web.1 connect=0ms service=1ms status=200 bytes=207 protocol=https
2019-08-15T16:15:33.426862+00:00 app[api]: Starting process with command `rails console` by user 07mikasanoyamani.idesitukikamo@gmail.com
2019-08-15T16:15:37.455814+00:00 heroku[run.7677]: Awaiting client
2019-08-15T16:15:37.498559+00:00 heroku[run.7677]: State changed from starting to up
2019-08-15T16:15:37.491472+00:00 heroku[run.7677]: Starting process with command `rails console`
2019-08-15T16:16:02.846345+00:00 heroku[run.7677]: State changed from up to complete
2019-08-15T16:16:02.826373+00:00 heroku[run.7677]: Process exited with status 0
2019-08-15T16:16:06.739265+00:00 heroku[router]: at=info method=GET path="/signup" host=vast-brushlands-26233.herokuapp.com request_id=c1d82439-5b64-4e38-8c2d-78105f12e334 fwd="46.193.65.129" dyno=web.1 connect=0ms service=8ms status=200 bytes=3427 protocol=https
2019-08-15T16:16:06.731853+00:00 app[web.1]: I, [2019-08-15T16:16:06.731767 #12]  INFO -- : [c1d82439-5b64-4e38-8c2d-78105f12e334] Started GET "/signup" for 46.193.65.129 at 2019-08-15 16:16:06 +0000
2019-08-15T16:16:06.732521+00:00 app[web.1]: I, [2019-08-15T16:16:06.732467 #12]  INFO -- : [c1d82439-5b64-4e38-8c2d-78105f12e334] Processing by UsersController#new as HTML
2019-08-15T16:16:06.733453+00:00 app[web.1]: I, [2019-08-15T16:16:06.733396 #12]  INFO -- : [c1d82439-5b64-4e38-8c2d-78105f12e334]   Rendering users/new.html.erb within layouts/application
2019-08-15T16:16:06.733966+00:00 app[web.1]: I, [2019-08-15T16:16:06.733914 #12]  INFO -- : [c1d82439-5b64-4e38-8c2d-78105f12e334]   Rendered shared/_error_messages.html.erb (0.1ms)
2019-08-15T16:16:06.735707+00:00 app[web.1]: I, [2019-08-15T16:16:06.735653 #12]  INFO -- : [c1d82439-5b64-4e38-8c2d-78105f12e334]   Rendered users/_form.html.erb (2.0ms)
2019-08-15T16:16:06.735822+00:00 app[web.1]: I, [2019-08-15T16:16:06.735775 #12]  INFO -- : [c1d82439-5b64-4e38-8c2d-78105f12e334]   Rendered users/new.html.erb within layouts/application (2.3ms)
2019-08-15T16:16:06.736366+00:00 app[web.1]: I, [2019-08-15T16:16:06.736317 #12]  INFO -- : [c1d82439-5b64-4e38-8c2d-78105f12e334]   Rendered layouts/_rails_default.html.erb (0.4ms)
2019-08-15T16:16:06.736553+00:00 app[web.1]: I, [2019-08-15T16:16:06.736506 #12]  INFO -- : [c1d82439-5b64-4e38-8c2d-78105f12e334]   Rendered layouts/_shim.html.erb (0.0ms)
2019-08-15T16:16:06.736914+00:00 app[web.1]: I, [2019-08-15T16:16:06.736866 #12]  INFO -- : [c1d82439-5b64-4e38-8c2d-78105f12e334]   Rendered layouts/_header.html.erb (0.2ms)
2019-08-15T16:16:06.737190+00:00 app[web.1]: I, [2019-08-15T16:16:06.737143 #12]  INFO -- : [c1d82439-5b64-4e38-8c2d-78105f12e334]   Rendered layouts/_footer.html.erb (0.1ms)
2019-08-15T16:16:06.737414+00:00 app[web.1]: I, [2019-08-15T16:16:06.737368 #12]  INFO -- : [c1d82439-5b64-4e38-8c2d-78105f12e334] Completed 200 OK in 5ms (Views: 4.1ms | ActiveRecord: 0.0ms)
2019-08-15T16:16:06.869260+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=vast-brushlands-26233.herokuapp.com request_id=d6afa18a-8b70-4c6f-8cf9-54fa5cfb621f fwd="46.193.65.129" dyno=web.1 connect=0ms service=4ms status=200 bytes=207 protocol=https
2019-08-15T16:16:56.857428+00:00 app[web.1]: I, [2019-08-15T16:16:56.857327 #12]  INFO -- : [23f62d32-a3f4-4c41-8410-3d971d48bde6] Started POST "/signup" for 46.193.65.129 at 2019-08-15 16:16:56 +0000
2019-08-15T16:16:56.858307+00:00 app[web.1]: I, [2019-08-15T16:16:56.858242 #12]  INFO -- : [23f62d32-a3f4-4c41-8410-3d971d48bde6] Processing by UsersController#create as HTML
2019-08-15T16:16:56.858416+00:00 app[web.1]: I, [2019-08-15T16:16:56.858340 #12]  INFO -- : [23f62d32-a3f4-4c41-8410-3d971d48bde6]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"xJ+dFaiRpKDE2UlcctidaxOt/S0y3CfhLb6TS3neQN43s6Ag43ASCpnDJzFAiB9wnLJAQAElvlsbfDJRToKQSQ==", "user"=>{"name"=>"Yuki", "email"=>"07mikasanoyamani.idesitukikamo@gmail.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Create my account"}
2019-08-15T16:16:56.952023+00:00 app[web.1]: D, [2019-08-15T16:16:56.951879 #12] DEBUG -- : [23f62d32-a3f4-4c41-8410-3d971d48bde6]    (1.3ms)  BEGIN
2019-08-15T16:16:56.962111+00:00 app[web.1]: D, [2019-08-15T16:16:56.962011 #12] DEBUG -- : [23f62d32-a3f4-4c41-8410-3d971d48bde6]   User Exists (1.5ms)  SELECT  1 AS one FROM "users" WHERE LOWER("users"."email") = LOWER($1) LIMIT $2  [["email", "07mikasanoyamani.idesitukikamo@gmail.com"], ["LIMIT", 1]]
2019-08-15T16:16:57.062754+00:00 app[web.1]: D, [2019-08-15T16:16:57.062574 #12] DEBUG -- : [23f62d32-a3f4-4c41-8410-3d971d48bde6]   SQL (2.6ms)  INSERT INTO "users" ("name", "email", "created_at", "updated_at", "password_digest", "activation_digest") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["name", "Yuki"], ["email", "07mikasanoyamani.idesitukikamo@gmail.com"], ["created_at", "2019-08-15 16:16:56.962457"], ["updated_at", "2019-08-15 16:16:56.962457"], ["password_digest", "$2a$10$1f05tdDYWD6gtkkT9Wcu1OxebMyaTNDSeuDY1OP1PNQmcBF0Ff03S"], ["activation_digest", "$2a$10$YoyG0BX6gAqurQoz4iXKN.lVlWYp8nJo6ZdfayJlbgYhZ3FE5d902"]]
2019-08-15T16:16:57.066054+00:00 app[web.1]: D, [2019-08-15T16:16:57.065963 #12] DEBUG -- : [23f62d32-a3f4-4c41-8410-3d971d48bde6]    (2.6ms)  COMMIT
2019-08-15T16:16:57.074978+00:00 app[web.1]: I, [2019-08-15T16:16:57.074904 #12]  INFO -- : [23f62d32-a3f4-4c41-8410-3d971d48bde6]   Rendering user_mailer/account_activation.html.erb within layouts/mailer
2019-08-15T16:16:57.077152+00:00 app[web.1]: I, [2019-08-15T16:16:57.077067 #12]  INFO -- : [23f62d32-a3f4-4c41-8410-3d971d48bde6]   Rendered user_mailer/account_activation.html.erb within layouts/mailer (2.0ms)
2019-08-15T16:16:57.078043+00:00 app[web.1]: I, [2019-08-15T16:16:57.077971 #12]  INFO -- : [23f62d32-a3f4-4c41-8410-3d971d48bde6]   Rendering user_mailer/account_activation.text.erb within layouts/mailer
2019-08-15T16:16:57.078993+00:00 app[web.1]: I, [2019-08-15T16:16:57.078916 #12]  INFO -- : [23f62d32-a3f4-4c41-8410-3d971d48bde6]   Rendered user_mailer/account_activation.text.erb within layouts/mailer (0.7ms)
2019-08-15T16:16:57.500030+00:00 heroku[router]: at=info method=POST path="/signup" host=vast-brushlands-26233.herokuapp.com request_id=23f62d32-a3f4-4c41-8410-3d971d48bde6 fwd="46.193.65.129" dyno=web.1 connect=3ms service=671ms status=500 bytes=1891 protocol=https
2019-08-15T16:16:57.382914+00:00 app[web.1]: D, [2019-08-15T16:16:57.382802 #12] DEBUG -- : [23f62d32-a3f4-4c41-8410-3d971d48bde6] UserMailer#account_activation: processed outbound mail in 314.5ms
2019-08-15T16:16:57.495236+00:00 app[web.1]: I, [2019-08-15T16:16:57.495113 #12]  INFO -- : [23f62d32-a3f4-4c41-8410-3d971d48bde6] Sent mail to 07mikasanoyamani.idesitukikamo@gmail.com (112.1ms)
2019-08-15T16:16:57.495247+00:00 app[web.1]: D, [2019-08-15T16:16:57.495208 #12] DEBUG -- : [23f62d32-a3f4-4c41-8410-3d971d48bde6] Date: Thu, 15 Aug 2019 16:16:57 +0000
2019-08-15T16:16:57.495250+00:00 app[web.1]: From: noreply@example.com
2019-08-15T16:16:57.495253+00:00 app[web.1]: To: 07mikasanoyamani.idesitukikamo@gmail.com
2019-08-15T16:16:57.495256+00:00 app[web.1]: Message-ID: <5d5585795ef04_c2ae80d749c4c647eb@45a18814-2bcb-402a-9a65-d45c7b6baedb.mail>
2019-08-15T16:16:57.495258+00:00 app[web.1]: Subject: Account activation
2019-08-15T16:16:57.495260+00:00 app[web.1]: Mime-Version: 1.0
2019-08-15T16:16:57.495263+00:00 app[web.1]: Content-Type: multipart/alternative;
2019-08-15T16:16:57.495265+00:00 app[web.1]: boundary="--==_mimepart_5d5585795ceab_c2ae80d749c4c646dc";
2019-08-15T16:16:57.495268+00:00 app[web.1]: charset=UTF-8
2019-08-15T16:16:57.495270+00:00 app[web.1]: Content-Transfer-Encoding: 7bit
2019-08-15T16:16:57.495272+00:00 app[web.1]: 
2019-08-15T16:16:57.495274+00:00 app[web.1]: 
2019-08-15T16:16:57.495276+00:00 app[web.1]: ----==_mimepart_5d5585795ceab_c2ae80d749c4c646dc
2019-08-15T16:16:57.495279+00:00 app[web.1]: Content-Type: text/plain;
2019-08-15T16:16:57.495281+00:00 app[web.1]: charset=UTF-8
2019-08-15T16:16:57.495283+00:00 app[web.1]: Content-Transfer-Encoding: 7bit
2019-08-15T16:16:57.495285+00:00 app[web.1]: 
2019-08-15T16:16:57.495287+00:00 app[web.1]: Hi Yuki,
2019-08-15T16:16:57.495289+00:00 app[web.1]: 
2019-08-15T16:16:57.495291+00:00 app[web.1]: Welcome to the Sample App! Click on the link below to activate your account:
2019-08-15T16:16:57.495293+00:00 app[web.1]: 
2019-08-15T16:16:57.495296+00:00 app[web.1]: https://vast-brushlands-26233.herokuapp.com/account_activations/C5CEmB8cbv_LeCpJgraoEg/edit?email=07mikasanoyamani.idesitukikamo%40gmail.com
2019-08-15T16:16:57.495298+00:00 app[web.1]: 
2019-08-15T16:16:57.495300+00:00 app[web.1]: ----==_mimepart_5d5585795ceab_c2ae80d749c4c646dc
2019-08-15T16:16:57.495302+00:00 app[web.1]: Content-Type: text/html;
2019-08-15T16:16:57.495304+00:00 app[web.1]: charset=UTF-8
2019-08-15T16:16:57.495306+00:00 app[web.1]: Content-Transfer-Encoding: 7bit
2019-08-15T16:16:57.495308+00:00 app[web.1]: 
2019-08-15T16:16:57.495310+00:00 app[web.1]: <!DOCTYPE html>
2019-08-15T16:16:57.495311+00:00 app[web.1]: <html>
2019-08-15T16:16:57.495313+00:00 app[web.1]: <head>
2019-08-15T16:16:57.495316+00:00 app[web.1]: <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
2019-08-15T16:16:57.495318+00:00 app[web.1]: <style>
2019-08-15T16:16:57.495320+00:00 app[web.1]: /* Email styles need to be inline */
2019-08-15T16:16:57.495322+00:00 app[web.1]: </style>
2019-08-15T16:16:57.495324+00:00 app[web.1]: </head>
2019-08-15T16:16:57.495325+00:00 app[web.1]: 
2019-08-15T16:16:57.495327+00:00 app[web.1]: <body>
2019-08-15T16:16:57.495329+00:00 app[web.1]: <h1>Sample App</h1>
2019-08-15T16:16:57.495332+00:00 app[web.1]: 
2019-08-15T16:16:57.495334+00:00 app[web.1]: <p>Hi Yuki,</p>
2019-08-15T16:16:57.495336+00:00 app[web.1]: 
2019-08-15T16:16:57.495338+00:00 app[web.1]: <p>
2019-08-15T16:16:57.495340+00:00 app[web.1]: Welcome to the Sample App! Click on the link below to activate your account:
2019-08-15T16:16:57.495343+00:00 app[web.1]: </p>
2019-08-15T16:16:57.495345+00:00 app[web.1]: 
2019-08-15T16:16:57.495348+00:00 app[web.1]: <a href="https://vast-brushlands-26233.herokuapp.com/account_activations/C5CEmB8cbv_LeCpJgraoEg/edit?email=07mikasanoyamani.idesitukikamo%40gmail.com">Activate</a>
2019-08-15T16:16:57.495350+00:00 app[web.1]: </body>
2019-08-15T16:16:57.495352+00:00 app[web.1]: </html>
2019-08-15T16:16:57.495354+00:00 app[web.1]: 
2019-08-15T16:16:57.495356+00:00 app[web.1]: ----==_mimepart_5d5585795ceab_c2ae80d749c4c646dc--
2019-08-15T16:16:57.495358+00:00 app[web.1]: 
2019-08-15T16:16:57.495841+00:00 app[web.1]: I, [2019-08-15T16:16:57.495772 #12]  INFO -- : [23f62d32-a3f4-4c41-8410-3d971d48bde6] Completed 500 Internal Server Error in 637ms (ActiveRecord: 10.3ms)
2019-08-15T16:16:57.498115+00:00 app[web.1]: F, [2019-08-15T16:16:57.498031 #12] FATAL -- : [23f62d32-a3f4-4c41-8410-3d971d48bde6]
2019-08-15T16:16:57.498298+00:00 app[web.1]: F, [2019-08-15T16:16:57.498121 #12] FATAL -- : [23f62d32-a3f4-4c41-8410-3d971d48bde6] Net::SMTPAuthenticationError (535 Authentication failed: account disabled
2019-08-15T16:16:57.498301+00:00 app[web.1]: ):
2019-08-15T16:16:57.498371+00:00 app[web.1]: F, [2019-08-15T16:16:57.498301 #12] FATAL -- : [23f62d32-a3f4-4c41-8410-3d971d48bde6]
2019-08-15T16:16:57.498451+00:00 app[web.1]: F, [2019-08-15T16:16:57.498385 #12] FATAL -- : [23f62d32-a3f4-4c41-8410-3d971d48bde6] app/models/user.rb:53:in `send_activation_email'
2019-08-15T16:16:57.498454+00:00 app[web.1]: [23f62d32-a3f4-4c41-8410-3d971d48bde6] app/controllers/users_controller.rb:23:in `create'
2019-08-15T16:16:57.610421+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=vast-brushlands-26233.herokuapp.com request_id=5df99ad7-0155-4a4b-8164-9fc2c89451ea fwd="46.193.65.129" dyno=web.1 connect=0ms service=2ms status=304 bytes=112 protocol=https
~~~

ログ内のユーザー認証リンク
https://vast-brushlands-26233.herokuapp.com/account_activations/C5CEmB8cbv_LeCpJgraoEg/edit?email=07mikasanoyamani.idesitukikamo%40gmail.com

を直接ブラウザに入力するとユーザーが認証されるが、認証メールは送られて来ない。

**Comment by YukiT1990** [comment]
（参考サイト）
https://qiita.com/yuta-ushijima/items/f43ef5e0b59c2510ff52

Heokuにログインし、デプロイしたアプリのOverViewｋら、SendGridへのリンクをクリック 

を行ったところ、

sendgrid.com へのアクセスが拒否されました このページを表示する権限がありません。 HTTP ERROR 403

というエラーになった。

heroku addons:destroy sendgrid:starter
を行った後、再度
heroku addons:create sendgrid:starter
を行ったところ、

~~~
Creating sendgrid:starter on ⬢ vast-brushlands-26233... !
 ▸    An error was encountered when contacting the add-on partner to
 ▸    create sendgrid:starter: Error Provisioning User - User status -
 ▸    banned
~~~

となり、SendGridのアカウント（有効化すらしていないが）が凍結（banned:禁止？）されたようである。
（ターミナルの画像）
https://gyazo.com/912413e3d45d810a952c882753171269


とりあえず
https://support.sendgrid.kke.co.jp/hc/ja?return_to=%2Fhc%2Frequests
からお問い合わせを送信した。

**Comment by YukiT1990** [comment]
その後SendGridの英語サイトから問い合わせるように言われたり、Herokuの方へ問い合わせるように言われたりしたが、結局

heroku addons:create sendgrid:starter

を行っても

~~~
Creating sendgrid:starter on ⬢ vast-brushlands-26233... !
 ▸    An error was encountered when contacting the add-on partner to
 ▸    create sendgrid:starter: Error Provisioning User - User status -
 ▸    banned
~~~
のままであった。
